<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'fernandos',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'posiblesprestadores',
  'published_date' => '2019-08-25 23:42:06',
  'type' => 'module',
  'version' => 1566776528,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'posiblesprestadores',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.posiblesprestadores.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.posiblesprestadores.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/en_us.lang.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/es_ES.lang.php',
      'to_module' => 'Leads',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Leadscodpostal_c' => 
    array (
      'id' => 'Leadscodpostal_c',
      'name' => 'codpostal_c',
      'label' => 'LBL_CODPOSTAL',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '15',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:38:34',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsdepto_c' => 
    array (
      'id' => 'Leadsdepto_c',
      'name' => 'depto_c',
      'label' => 'LBL_DEPTO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:38:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsespecialidad_c' => 
    array (
      'id' => 'Leadsespecialidad_c',
      'name' => 'especialidad_c',
      'label' => 'LBL_ESPECIALIDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Espe_Especialidades',
      'ext3' => 'espe_especialidades_id_c',
      'ext4' => '',
    ),
    'Leadsespe_especialidades_id_c' => 
    array (
      'id' => 'Leadsespe_especialidades_id_c',
      'name' => 'espe_especialidades_id_c',
      'label' => 'LBL_ESPECIALIDAD_ESPE_ESPECIALIDADES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_address_c' => 
    array (
      'id' => 'Leadsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Leadsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_lat_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsjjwg_maps_lng_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadslocalidadprestacion_c' => 
    array (
      'id' => 'Leadslocalidadprestacion_c',
      'name' => 'localidadprestacion_c',
      'label' => 'LBL_LOCALIDADPRESTACION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:43:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Loc_Localidades',
      'ext3' => 'loc_localidades_id1_c',
      'ext4' => '',
    ),
    'Leadslocalidad_c' => 
    array (
      'id' => 'Leadslocalidad_c',
      'name' => 'localidad_c',
      'label' => 'LBL_LOCALIDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Loc_Localidades',
      'ext3' => 'loc_localidades_id_c',
      'ext4' => '',
    ),
    'Leadsloc_localidades_id1_c' => 
    array (
      'id' => 'Leadsloc_localidades_id1_c',
      'name' => 'loc_localidades_id1_c',
      'label' => 'LBL_LOCALIDADPRESTACION_LOC_LOCALIDADES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:43:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsloc_localidades_id_c' => 
    array (
      'id' => 'Leadsloc_localidades_id_c',
      'name' => 'loc_localidades_id_c',
      'label' => 'LBL_LOCALIDAD_LOC_LOCALIDADES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsmunicipioprestacion_c' => 
    array (
      'id' => 'Leadsmunicipioprestacion_c',
      'name' => 'municipioprestacion_c',
      'label' => 'LBL_MUNICIPIOPRESTACION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:42:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'muni_Municipios',
      'ext3' => 'muni_municipios_id1_c',
      'ext4' => '',
    ),
    'Leadsmunicipio_c' => 
    array (
      'id' => 'Leadsmunicipio_c',
      'name' => 'municipio_c',
      'label' => 'LBL_MUNICIPIO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'muni_Municipios',
      'ext3' => 'muni_municipios_id_c',
      'ext4' => '',
    ),
    'Leadsmuni_municipios_id1_c' => 
    array (
      'id' => 'Leadsmuni_municipios_id1_c',
      'name' => 'muni_municipios_id1_c',
      'label' => 'LBL_MUNICIPIOPRESTACION_MUNI_MUNICIPIOS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:42:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsmuni_municipios_id_c' => 
    array (
      'id' => 'Leadsmuni_municipios_id_c',
      'name' => 'muni_municipios_id_c',
      'label' => 'LBL_MUNICIPIO_MUNI_MUNICIPIOS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:40:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnombrecalle_c' => 
    array (
      'id' => 'Leadsnombrecalle_c',
      'name' => 'nombrecalle_c',
      'label' => 'LBL_NOMBRECALLE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:36:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnrodoc_c' => 
    array (
      'id' => 'Leadsnrodoc_c',
      'name' => 'nrodoc_c',
      'label' => 'LBL_NRODOC',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:44:05',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnromatricula_c' => 
    array (
      'id' => 'Leadsnromatricula_c',
      'name' => 'nromatricula_c',
      'label' => 'LBL_NROMATRICULA',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:44:36',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsnumerocalle_c' => 
    array (
      'id' => 'Leadsnumerocalle_c',
      'name' => 'numerocalle_c',
      'label' => 'LBL_NUMEROCALLE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:37:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsobcdomicilio_c' => 
    array (
      'id' => 'Leadsobcdomicilio_c',
      'name' => 'obcdomicilio_c',
      'label' => 'LBL_OBCDOMICILIO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:39:12',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspaisprestacion_c' => 
    array (
      'id' => 'Leadspaisprestacion_c',
      'name' => 'paisprestacion_c',
      'label' => 'LBL_PAISPRESTACION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:41:28',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Pais_Paises',
      'ext3' => 'pais_paises_id1_c',
      'ext4' => '',
    ),
    'Leadspais_c' => 
    array (
      'id' => 'Leadspais_c',
      'name' => 'pais_c',
      'label' => 'LBL_PAIS',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:39:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Pais_Paises',
      'ext3' => 'pais_paises_id_c',
      'ext4' => '',
    ),
    'Leadspais_paises_id1_c' => 
    array (
      'id' => 'Leadspais_paises_id1_c',
      'name' => 'pais_paises_id1_c',
      'label' => 'LBL_PAISPRESTACION_PAIS_PAISES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:41:28',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspais_paises_id_c' => 
    array (
      'id' => 'Leadspais_paises_id_c',
      'name' => 'pais_paises_id_c',
      'label' => 'LBL_PAIS_PAIS_PAISES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:39:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadspiso_c' => 
    array (
      'id' => 'Leadspiso_c',
      'name' => 'piso_c',
      'label' => 'LBL_PISO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 18:37:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsprovinciaprestacion_c' => 
    array (
      'id' => 'Leadsprovinciaprestacion_c',
      'name' => 'provinciaprestacion_c',
      'label' => 'LBL_PROVINCIAPRESTACION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:42:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'prov_Provincias',
      'ext3' => 'prov_provincias_id1_c',
      'ext4' => '',
    ),
    'Leadsprovincia_c' => 
    array (
      'id' => 'Leadsprovincia_c',
      'name' => 'provincia_c',
      'label' => 'LBL_PROVINCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:39:58',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'prov_Provincias',
      'ext3' => 'prov_provincias_id_c',
      'ext4' => '',
    ),
    'Leadsprov_provincias_id1_c' => 
    array (
      'id' => 'Leadsprov_provincias_id1_c',
      'name' => 'prov_provincias_id1_c',
      'label' => 'LBL_PROVINCIAPRESTACION_PROV_PROVINCIAS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:42:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadsprov_provincias_id_c' => 
    array (
      'id' => 'Leadsprov_provincias_id_c',
      'name' => 'prov_provincias_id_c',
      'label' => 'LBL_PROVINCIA_PROV_PROVINCIAS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 18:39:58',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadstipodoc_c' => 
    array (
      'id' => 'Leadstipodoc_c',
      'name' => 'tipodoc_c',
      'label' => 'LBL_TIPODOC',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'DNI',
      'date_modified' => '2019-08-22 18:43:41',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_TipoDocumento',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/modules/Leads/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Leads/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/listviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/popupdefs.php',
      'to' => 'custom/modules/Leads/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Leads/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Leads/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/searchdefs.php',
      'to' => 'custom/modules/Leads/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_espe_especialidades_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_espe_especialidades_id_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_depto_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_depto_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_obcdomicilio_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_obcdomicilio_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_provincia_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_provincia_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_paises_id1_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_paises_id1_c.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_numerocalle_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_numerocalle_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_provinciaprestacion_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_provinciaprestacion_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_prov_provincias_id1_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_prov_provincias_id1_c.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nombrecalle_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nombrecalle_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_tipodoc_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_tipodoc_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nromatricula_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nromatricula_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_localidad_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_localidad_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_codpostal_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_codpostal_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_localidadprestacion_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_localidadprestacion_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nrodoc_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_nrodoc_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_paisprestacion_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_paisprestacion_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_municipio_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_municipio_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_muni_municipios_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_muni_municipios_id_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_paises_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_pais_paises_id_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_municipioprestacion_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_municipioprestacion_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_muni_municipios_id1_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_muni_municipios_id1_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_prov_provincias_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_prov_provincias_id_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_especialidad_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_especialidad_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_loc_localidades_id_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_loc_localidades_id_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_loc_localidades_id1_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_loc_localidades_id1_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_piso_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/_override_sugarfield_piso_c.php',
    ),
  ),
);