<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'fernandos',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Documentacion',
  'published_date' => '2019-08-25 23:42:53',
  'type' => 'module',
  'version' => 1566776574,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Documentacion',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Documentacion.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Documentacion.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/language/en_us.lang.php',
      'to_module' => 'Documents',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/language/es_ES.lang.php',
      'to_module' => 'Documents',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Documentsestadodocumentacion_c' => 
    array (
      'id' => 'Documentsestadodocumentacion_c',
      'name' => 'estadodocumentacion_c',
      'label' => 'LBL_ESTADODOCUMENTACION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Documents',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'REV',
      'date_modified' => '2019-08-22 22:44:48',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Estado_Documentacion',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Documentstipodocumentacion_c' => 
    array (
      'id' => 'Documentstipodocumentacion_c',
      'name' => 'tipodocumentacion_c',
      'label' => 'LBL_TIPODOCUMENTACION',
      'comments' => '',
      'help' => '',
      'module' => 'Documents',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'DNI00',
      'date_modified' => '2019-08-22 22:43:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Tipo_Documentacion',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/SearchFields.php',
      'to' => 'custom/modules/Documents/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Documents/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Documents/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Documents/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Documents/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Documents/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/editviewdefs.php',
      'to' => 'custom/modules/Documents/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Documents/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/listviewdefs.php',
      'to' => 'custom/modules/Documents/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/popupdefs.php',
      'to' => 'custom/modules/Documents/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Documents/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Documents/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Documents/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/searchdefs.php',
      'to' => 'custom/modules/Documents/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Documents/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Documents/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_tipodocumentacion_c.php',
      'to' => 'custom/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_tipodocumentacion_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_active_date.php',
      'to' => 'custom/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_active_date.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_estadodocumentacion_c.php',
      'to' => 'custom/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_estadodocumentacion_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_exp_date.php',
      'to' => 'custom/Extension/modules/Documents/Ext/Vardefs/_override_sugarfield_exp_date.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Documents/Ext/Layoutdefs/_overrideDocument_subpanel_contacts.php',
      'to' => 'custom/Extension/modules/Documents/Ext/Layoutdefs/_overrideDocument_subpanel_contacts.php',
    ),
  ),
);