<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'fernandos',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Prestadores',
  'published_date' => '2019-08-26 13:58:41',
  'type' => 'module',
  'version' => 1566827925,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Prestadores',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Prestadores.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Prestadores.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/language/en_us.lang.php',
      'to_module' => 'Contacts',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/language/es_ES.lang.php',
      'to_module' => 'Contacts',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Contactscodpostal_c' => 
    array (
      'id' => 'Contactscodpostal_c',
      'name' => 'codpostal_c',
      'label' => 'LBL_CODPOSTAL',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '15',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:15:17',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactscontact_id_c' => 
    array (
      'id' => 'Contactscontact_id_c',
      'name' => 'contact_id_c',
      'label' => 'LBL_REFERIDOPOR_CONTACT_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-23 21:56:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsdepto_c' => 
    array (
      'id' => 'Contactsdepto_c',
      'name' => 'depto_c',
      'label' => 'LBL_DEPTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:14:58',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsestado_prestador_c' => 
    array (
      'id' => 'Contactsestado_prestador_c',
      'name' => 'estado_prestador_c',
      'label' => 'LBL_ESTADO_PRESTADOR',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'Nuevo',
      'date_modified' => '2019-08-23 21:57:48',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Estado_Prestador',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsfechabaja_c' => 
    array (
      'id' => 'Contactsfechabaja_c',
      'name' => 'fechabaja_c',
      'label' => 'LBL_FECHABAJA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 22:06:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsfnacimiento_c' => 
    array (
      'id' => 'Contactsfnacimiento_c',
      'name' => 'fnacimiento_c',
      'label' => 'LBL_FNACIMIENTO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 21:56:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_address_c' => 
    array (
      'id' => 'Contactsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Contactsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_lat_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsjjwg_maps_lng_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactslocalidad_c' => 
    array (
      'id' => 'Contactslocalidad_c',
      'name' => 'localidad_c',
      'label' => 'LBL_LOCALIDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:17:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Loc_Localidades',
      'ext3' => 'loc_localidades_id_c',
      'ext4' => '',
    ),
    'Contactsloc_localidades_id_c' => 
    array (
      'id' => 'Contactsloc_localidades_id_c',
      'name' => 'loc_localidades_id_c',
      'label' => 'LBL_LOCALIDAD_LOC_LOCALIDADES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:17:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsmapa_prestador_c' => 
    array (
      'id' => 'Contactsmapa_prestador_c',
      'name' => 'mapa_prestador_c',
      'label' => 'LBL_MAPA_PRESTADOR',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Contacts',
      'type' => 'iframe',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q={nombrecalle_c},{numerocalle_c}, {localidad_c}&aq=&iwloc=A&output=embed',
      'date_modified' => '2019-08-23 22:02:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => '1',
      'ext4' => '200',
    ),
    'Contactsmotivobaja_c' => 
    array (
      'id' => 'Contactsmotivobaja_c',
      'name' => 'motivobaja_c',
      'label' => 'LBL_MOTIVOBAJA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2019-08-23 22:05:26',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Motivos_Baja',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsmotivocancelacion_c' => 
    array (
      'id' => 'Contactsmotivocancelacion_c',
      'name' => 'motivocancelacion_c',
      'label' => 'LBL_MOTIVOCANCELACION',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 22:07:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Motivos_Cancelacion',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsmunicipio_c' => 
    array (
      'id' => 'Contactsmunicipio_c',
      'name' => 'municipio_c',
      'label' => 'LBL_MUNICIPIO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:17:02',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'muni_Municipios',
      'ext3' => 'muni_municipios_id_c',
      'ext4' => '',
    ),
    'Contactsmuni_municipios_id_c' => 
    array (
      'id' => 'Contactsmuni_municipios_id_c',
      'name' => 'muni_municipios_id_c',
      'label' => 'LBL_MUNICIPIO_MUNI_MUNICIPIOS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:17:02',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnacionalidad_c' => 
    array (
      'id' => 'Contactsnacionalidad_c',
      'name' => 'nacionalidad_c',
      'label' => 'LBL_NACIONALIDAD',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-23 21:55:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Naci_Nacionalidades',
      'ext3' => 'naci_nacionalidades_id_c',
      'ext4' => '',
    ),
    'Contactsnaci_nacionalidades_id_c' => 
    array (
      'id' => 'Contactsnaci_nacionalidades_id_c',
      'name' => 'naci_nacionalidades_id_c',
      'label' => 'LBL_NACIONALIDAD_NACI_NACIONALIDADES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-23 21:55:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnombrecalle_c' => 
    array (
      'id' => 'Contactsnombrecalle_c',
      'name' => 'nombrecalle_c',
      'label' => 'LBL_NOMBRECALLE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:12:57',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnotasbaja_c' => 
    array (
      'id' => 'Contactsnotasbaja_c',
      'name' => 'notasbaja_c',
      'label' => 'LBL_NOTASBAJA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 22:06:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => '',
    ),
    'Contactsnotascancelacion_c' => 
    array (
      'id' => 'Contactsnotascancelacion_c',
      'name' => 'notascancelacion_c',
      'label' => 'LBL_NOTASCANCELACION',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 22:07:42',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => '',
    ),
    'Contactsnrodoc_c' => 
    array (
      'id' => 'Contactsnrodoc_c',
      'name' => 'nrodoc_c',
      'label' => 'LBL_NRODOC',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2019-08-23 21:55:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsnumerocalle_c' => 
    array (
      'id' => 'Contactsnumerocalle_c',
      'name' => 'numerocalle_c',
      'label' => 'LBL_NUMEROCALLE',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:14:24',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsobsdomicilio_c' => 
    array (
      'id' => 'Contactsobsdomicilio_c',
      'name' => 'obsdomicilio_c',
      'label' => 'LBL_OBSDOMICILIO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:15:41',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsobsestado_c' => 
    array (
      'id' => 'Contactsobsestado_c',
      'name' => 'obsestado_c',
      'label' => 'LBL_OBSESTADO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-23 21:58:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => '',
    ),
    'Contactsorigenbaja_c' => 
    array (
      'id' => 'Contactsorigenbaja_c',
      'name' => 'origenbaja_c',
      'label' => 'LBL_ORIGENBAJA',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2019-08-23 22:04:32',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Origen_Baja',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactspais_c' => 
    array (
      'id' => 'Contactspais_c',
      'name' => 'pais_c',
      'label' => 'LBL_PAIS',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:16:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Pais_Paises',
      'ext3' => 'pais_paises_id_c',
      'ext4' => '',
    ),
    'Contactspais_paises_id_c' => 
    array (
      'id' => 'Contactspais_paises_id_c',
      'name' => 'pais_paises_id_c',
      'label' => 'LBL_PAIS_PAIS_PAISES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:16:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactspiso_c' => 
    array (
      'id' => 'Contactspiso_c',
      'name' => 'piso_c',
      'label' => 'LBL_PISO',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-22 23:14:40',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsprovincia_c' => 
    array (
      'id' => 'Contactsprovincia_c',
      'name' => 'provincia_c',
      'label' => 'LBL_PROVINCIA',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:16:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'prov_Provincias',
      'ext3' => 'prov_provincias_id_c',
      'ext4' => '',
    ),
    'Contactsprov_provincias_id_c' => 
    array (
      'id' => 'Contactsprov_provincias_id_c',
      'name' => 'prov_provincias_id_c',
      'label' => 'LBL_PROVINCIA_PROV_PROVINCIAS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-22 23:16:21',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Contactsreferidopor_c' => 
    array (
      'id' => 'Contactsreferidopor_c',
      'name' => 'referidopor_c',
      'label' => 'LBL_REFERIDOPOR',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-23 21:56:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Contacts',
      'ext3' => 'contact_id_c',
      'ext4' => '',
    ),
    'Contactstipodoc_c' => 
    array (
      'id' => 'Contactstipodoc_c',
      'name' => 'tipodoc_c',
      'label' => 'LBL_TIPODOC',
      'comments' => '',
      'help' => '',
      'module' => 'Contacts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'DNI',
      'date_modified' => '2019-08-23 21:54:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_TipoDocumento',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/modules/Contacts/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Contacts/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Contacts/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/popupdefs.php',
      'to' => 'custom/modules/Contacts/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Contacts/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/modules/Contacts/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Contacts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Contacts/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_depto_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_depto_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_mapa_prestador_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_mapa_prestador_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_naci_nacionalidades_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_naci_nacionalidades_id_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nacionalidad_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nacionalidad_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_provincia_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_provincia_c.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_obsestado_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_obsestado_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_numerocalle_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_numerocalle_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_fnacimiento_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_fnacimiento_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nombrecalle_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nombrecalle_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_fechabaja_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_fechabaja_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_tipodoc_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_tipodoc_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_pais_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_pais_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_referidopor_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_referidopor_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_notascancelacion_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_notascancelacion_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_obsdomicilio_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_obsdomicilio_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_localidad_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_localidad_c.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_origenbaja_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_origenbaja_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_codpostal_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_codpostal_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nrodoc_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_nrodoc_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_municipio_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_municipio_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_contact_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_contact_id_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_muni_municipios_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_muni_municipios_id_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_pais_paises_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_pais_paises_id_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_estado_prestador_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_estado_prestador_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_motivobaja_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_motivobaja_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_motivocancelacion_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_motivocancelacion_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_prov_provincias_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_prov_provincias_id_c.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_loc_localidades_id_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_loc_localidades_id_c.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_piso_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_piso_c.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_notasbaja_c.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Vardefs/_override_sugarfield_notasbaja_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/Contacts/Ext/Layoutdefs/_overrideContact_subpanel_documents.php',
      'to' => 'custom/Extension/modules/Contacts/Ext/Layoutdefs/_overrideContact_subpanel_documents.php',
    ),
  ),
);