<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'fernandos',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Facturacion',
  'published_date' => '2019-08-26 13:59:24',
  'type' => 'module',
  'version' => 1566827967,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Facturacion',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Facturacion.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.Facturacion.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/language/en_us.lang.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/language/es_ES.lang.php',
      'to_module' => 'Accounts',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Accountsaliasc1_c' => 
    array (
      'id' => 'Accountsaliasc1_c',
      'name' => 'aliasc1_c',
      'label' => 'LBL_ALIASC1',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 02:11:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsaliasc2_c' => 
    array (
      'id' => 'Accountsaliasc2_c',
      'name' => 'aliasc2_c',
      'label' => 'LBL_ALIASC2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 02:12:11',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsbancoc1_c' => 
    array (
      'id' => 'Accountsbancoc1_c',
      'name' => 'bancoc1_c',
      'label' => 'LBL_BANCOC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 01:33:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'Banco_Bancos',
      'ext3' => 'banco_bancos_id_c',
      'ext4' => '',
    ),
    'Accountsbancoc2_c' => 
    array (
      'id' => 'Accountsbancoc2_c',
      'name' => 'bancoc2_c',
      'label' => 'LBL_BANCOC2',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 02:23:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Banco_Bancos',
      'ext3' => 'banco_bancos_id1_c',
      'ext4' => NULL,
    ),
    'Accountsbanco_bancos_id1_c' => 
    array (
      'id' => 'Accountsbanco_bancos_id1_c',
      'name' => 'banco_bancos_id1_c',
      'label' => 'LBL_BANCOC2_BANCO_BANCOS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 02:09:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsbanco_bancos_id_c' => 
    array (
      'id' => 'Accountsbanco_bancos_id_c',
      'name' => 'banco_bancos_id_c',
      'label' => 'LBL_BANCOC1_BANCO_BANCOS_ID',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 01:33:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountscbucuenta1_c' => 
    array (
      'id' => 'Accountscbucuenta1_c',
      'name' => 'cbucuenta1_c',
      'label' => 'LBL_CBUCUENTA1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:34:46',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountscbucuenta2_c' => 
    array (
      'id' => 'Accountscbucuenta2_c',
      'name' => 'cbucuenta2_c',
      'label' => 'LBL_CBUCUENTA2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 02:11:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsidtitularc1_c' => 
    array (
      'id' => 'Accountsidtitularc1_c',
      'name' => 'idtitularc1_c',
      'label' => 'LBL_IDTITULARC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:33:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsjjwg_maps_address_c' => 
    array (
      'id' => 'Accountsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Accountsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsjjwg_maps_lat_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsjjwg_maps_lng_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-07-02 15:44:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsnrocuentac1_c' => 
    array (
      'id' => 'Accountsnrocuentac1_c',
      'name' => 'nrocuentac1_c',
      'label' => 'LBL_NROCUENTAC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:34:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsnrocuentac2_c' => 
    array (
      'id' => 'Accountsnrocuentac2_c',
      'name' => 'nrocuentac2_c',
      'label' => 'LBL_NROCUENTAC2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 02:11:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsnroidentificacionc1_c' => 
    array (
      'id' => 'Accountsnroidentificacionc1_c',
      'name' => 'nroidentificacionc1_c',
      'label' => 'LBL_NROIDENTIFICACIONC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 02:08:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsnroidentificacionc2_c' => 
    array (
      'id' => 'Accountsnroidentificacionc2_c',
      'name' => 'nroidentificacionc2_c',
      'label' => 'LBL_NROIDENTIFICACIONC2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 02:08:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsnroidentificacion_c' => 
    array (
      'id' => 'Accountsnroidentificacion_c',
      'name' => 'nroidentificacion_c',
      'label' => 'LBL_NROIDENTIFICACION',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:28:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsobsdomicilio_c' => 
    array (
      'id' => 'Accountsobsdomicilio_c',
      'name' => 'obsdomicilio_c',
      'label' => 'LBL_OBSDOMICILIO',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:28:57',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => '',
    ),
    'Accountsquienfactura_c' => 
    array (
      'id' => 'Accountsquienfactura_c',
      'name' => 'quienfactura_c',
      'label' => 'LBL_QUIENFACTURA',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'Prestador',
      'date_modified' => '2019-08-24 01:26:17',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Quien_Factura',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsrazonsocial_c' => 
    array (
      'id' => 'Accountsrazonsocial_c',
      'name' => 'razonsocial_c',
      'label' => 'LBL_RAZONSOCIAL',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:27:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountssucursalc1_c' => 
    array (
      'id' => 'Accountssucursalc1_c',
      'name' => 'sucursalc1_c',
      'label' => 'LBL_SUCURSALC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:34:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountssucursalc2_c' => 
    array (
      'id' => 'Accountssucursalc2_c',
      'name' => 'sucursalc2_c',
      'label' => 'LBL_SUCURSALC2',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-08-24 02:10:17',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountstipoidentificacionc1_c' => 
    array (
      'id' => 'Accountstipoidentificacionc1_c',
      'name' => 'tipoidentificacionc1_c',
      'label' => 'LBL_TIPOIDENTIFICACIONC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'CUIT',
      'date_modified' => '2019-08-24 01:32:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Tipo_Identificacion',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountstipoidentificacionc2_c' => 
    array (
      'id' => 'Accountstipoidentificacionc2_c',
      'name' => 'tipoidentificacionc2_c',
      'label' => 'LBL_TIPOIDENTIFICACIONC2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'CUIT',
      'date_modified' => '2019-08-24 02:06:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Tipo_Identificacion',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountstipoidentificacion_c' => 
    array (
      'id' => 'Accountstipoidentificacion_c',
      'name' => 'tipoidentificacion_c',
      'label' => 'LBL_TIPOIDENTIFICACION',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'CUIT',
      'date_modified' => '2019-08-24 01:27:50',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'aDom_Tipo_Identificacion',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountstitularc1_c' => 
    array (
      'id' => 'Accountstitularc1_c',
      'name' => 'titularc1_c',
      'label' => 'LBL_TITULARC1',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:29:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountstitularc2_c' => 
    array (
      'id' => 'Accountstitularc2_c',
      'name' => 'titularc2_c',
      'label' => 'LBL_TITULARC2',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-08-24 01:35:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/SearchFields.php',
      'to' => 'custom/modules/Accounts/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Accounts/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/popupdefs.php',
      'to' => 'custom/modules/Accounts/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/modules/Accounts/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nrocuentac2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nrocuentac2_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacion_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacion_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_sucursalc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_sucursalc2_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_banco_bancos_id_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_banco_bancos_id_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lng_c.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_quienfactura_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_quienfactura_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_lat_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_cbucuenta2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_cbucuenta2_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_titularc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_titularc1_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_razonsocial_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_razonsocial_c.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_obsdomicilio_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_obsdomicilio_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_sucursalc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_sucursalc1_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_phone_office.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_phone_office.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_address_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_aliasc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_aliasc2_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_cbucuenta1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_cbucuenta1_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacionc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacionc1_c.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacion_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacion_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_aliasc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_aliasc1_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacionc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nroidentificacionc2_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_bancoc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_bancoc1_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_name.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_name.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_banco_bancos_id1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_banco_bancos_id1_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacionc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacionc1_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_idtitularc1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_idtitularc1_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_bancoc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_bancoc2_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacionc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_tipoidentificacionc2_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nrocuentac1_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_nrocuentac1_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_titularc2_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/_override_sugarfield_titularc2_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Layoutdefs/_overrideAccount_subpanel_opportunities.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Layoutdefs/_overrideAccount_subpanel_opportunities.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Layoutdefs/_overrideAccount_subpanel_contacts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Layoutdefs/_overrideAccount_subpanel_contacts.php',
    ),
  ),
);